### ISSUE TITLE
feature: just worst ranked solves

### ISSUE THREAD

**Issue by eff96** [jonatanklosko/wca_statistics#7]
just the person, the rank, the event, single or average, that's all.

**Comment by jonatanklosko** [comment]
If I understand correctly you mean normal rankings, but upside down. In this case I don't think it's a valuable ranking, because competitions have time limits (an upper bound for a result), for 3x3x3 it's usually 10 minutes. Also, calculating this ranking would take relatively long as compared to other ones, so I'd say it's not worth it.
